import { test, expect } from '@playwright/test';

test('test to-do app @sanity', async ({ page }) => {
  await page.goto('https://todomvc.com/examples/react/dist/');
  await page.getByTestId('text-input').click();
  await page.getByTestId('text-input').fill('go for walk');
  await page.getByTestId('text-input').press('Enter');
  await page.getByTestId('text-input').fill('buy grosy');
  await page.getByTestId('text-input').press('Enter');
  await page.getByTestId('text-input').fill('learn to photoshp');
  await page.getByTestId('text-input').press('Enter');
  await page.getByTestId('text-input').fill('learn to playwright');
  await page.getByTestId('text-input').press('Enter');
  await page.getByRole('listitem').filter({ hasText: 'go for walk' }).getByTestId('todo-item-toggle').check();
  await page.getByRole('listitem').filter({ hasText: 'buy grosy' }).getByTestId('todo-item-toggle').check();
  await page.getByRole('listitem').filter({ hasText: 'learn to photoshp' }).getByTestId('todo-item-toggle').check();
  await page.getByRole('listitem').filter({ hasText: 'learn to playwright' }).getByTestId('todo-item-toggle').check();
  await page.getByRole('link', { name: 'Active' }).click();
  await page.getByRole('link', { name: 'Completed' }).click();
  await page.getByText('learn to photoshp').click();
  await page.getByRole('link', { name: 'Active' }).click();
  await page.getByRole('link', { name: 'All' }).click();
  await page.getByRole('listitem').filter({ hasText: 'go for walk' }).getByTestId('todo-item-toggle').uncheck();
  await page.getByText('learn to photoshp').click();
  await page.getByRole('link', { name: 'Completed' }).click();
  await page.getByText('learn to photoshp').click();
  await page.getByRole('link', { name: 'Completed' }).click();
 // await page.getByRole('listitem').filter({ hasText: 'learn to photoshp' }).getByTestId('todo-item-toggle').uncheck();
  await page.goto('https://todomvc.com/examples/react/dist/#/active');
  await page.getByRole('link', { name: 'All' }).click();
  await page.getByRole('link', { name: 'Active' }).click();
  await page.getByRole('link', { name: 'Completed' }).click();
  await page.getByRole('link', { name: 'Active' }).click();
  await page.getByRole('link', { name: 'All' }).click();
  await expect(page.getByText('go for walk')).toBeVisible();
  await page.getByText('learn to photoshp').click();
  await expect(page.getByTestId('todo-list')).toContainText('go for walk');
  await page.getByText('learn to photoshp').click();
 //await expect(page.getByTestId('todo-list')).toContainText('learn to photoshp 1');
});